### ISSUE TITLE
iFrame Block: Left/Right Alignment Ignored

### ISSUE THREAD

**Issue by allykmyta** [Automattic/newspack-blocks#1058]
**Describe the bug**
When iFrame block is assigned to the left or right, the changes do not apply to the frontend of the site.

**To Reproduce**
1. Go to a post
2. Add iFrame Block, select "embed from URL", enter URL (I used Google Maps URL)
3. Align iFrame block to the right or left
4. Make sure that "fullscreen" toggle isn't selected
5. Publish and preview post

**Screenshots**
Image of editor and iFrame aligned to the right:
<img width="937" alt="Screen Shot 2022-03-06 at 11 34 42" src="https://user-images.githubusercontent.com/35075802/156939465-085a78c7-5605-4d72-926d-837afe7010bf.png">

Front end result:

![Screen Shot on 2022-03-06 at 11:36:27](https://user-images.githubusercontent.com/35075802/156939487-832f2d64-7d75-4189-bae8-36a70c874635.png)

**Expected behavior**
The iFrame block should be aligned to the left or right depending on how it was set rather than appearing full width.

**Comment by laurelfulford** [comment]
Hi @allykmyta! This sounds like it might be related to the same issue as this PR, which has to do with the alignments not working: https://github.com/Automattic/newspack-blocks/pull/1050

However, I actually suggested removing the left and right alignments there both because they weren't working and because they seemed like kind of an odd option for an iframe, and that full-width would be a lot more common 😬 I'm kind of double-guessing that suggestion now, though. Are you finding people are trying to do this a lot? 

Either way, in the short-term, nesting the iframe in the group block and floating it left or right should do the trick -- you just need to give the iframe a `px` width rather than leaving it at 100% -- otherwise, the iframe "collapses" on AMP pages. I think this happens because between the iframe's 100% width, and the floated group block's max-width of 50%, the amp-frame maths things out and decides it should be 0%.

**Comment by allykmyta** [comment]
> Are you finding people are trying to do this a lot?

@laurelfulford You're right, it's definitely more common to see iFrames in full-width. I don't see this ask very often so the workaround you provided would suffice.  If that changes sometime in the future and we see an increase in requests, we can feature request it.  And thank you for linking the PR!!

**Comment by laurelfulford** [comment]
Thanks @allykmyta! 

I'm going to close this issue, as it should be resolved with #1050 (at least, the non-working left and right alignments will be gone, along with the wide and full alignments now working!). 

We can reopen, or spin up a fresh issue if this keeps coming up after that :)
