### ISSUE TITLE
Author Profile & List: Add Title field

### ISSUE THREAD

**Issue by tmmbecker** [Automattic/newspack-blocks#1166]
We've added support for the Title field in the author bio [in the theme](https://github.com/Automattic/newspack-theme/issues/1803). Per Oaklandside, it would be useful to mimic this and have the Title as an option in the Settings for the Author Profile & List blocks as well.

**Comment by laurelfulford** [comment]
Just to add some context: the theme displays the Title field that's added through the Trust Indicators plugin -- a title field isn't available for WordPress users by default, so the current theme implementation is limited to publishers who are in the Trust Project and have the Trust Indicators plugin installed. 

If this should be available to publishers that aren't part of the Trust Project, we'll need to add our own 'Title' field (maybe through the Newspack Plugin?) and add support for that to the blocks and the theme. We may also want to extend Trust Indicators support to the blocks as well, just so the two fields (the title coming from Newspack and the title coming from Trust Indicators) behave consistently across the theme and blocks.

**Comment by yogeshbeniwal** [comment]
@tmmbecker This is in Yoast SEO Premium Addon rather than Yoast SEO main plugin. How many of the publishers are/will be using it?

**Comment by tmmbecker** [comment]
Currently 36 sites have Yoast Premium. Far more than use Trust Indicators :)

**Comment by aschweigert** [comment]
I don't think we should depend on Yoast or Trust Indicators for this. I'm a little ambivalent about CAP, but in general, just having a single field for job title that works for all authors (and guest authors) is a feature I think we should support, because whether or not an org is participating in the Trust Project, job title in a signal that is used to establish trust with readers, and, [as I noted in this post](pamTN9-40h-p2#:~:text=You%20might%20notice%20that%20the%20author%20bio%20section%20is%20missing%20here.), something I think we should include in the byline at the top of articles to alleviate the need (or desire) to show a longer author bio at the bottom of articles since that space should generally be put to better use.

**Comment by aschweigert** [comment]
> would that feature be introduced by Newspack Blocks, or by Newspack Plugin?

Seems like it would probably be in the Newspack plugin so that the fields would be available for use by our custom blocks, themes, etc.

**Comment by margaretschneider** [comment]
Adding a data point: Reveal has also requested the ability to add Job Title in the Author Profile block, which would be supported by the proposed updates to the Newspack plugin and subsequently this block.
