### ISSUE TITLE
[epic/ras-acc branch] "cover fees" option clears CC form details

### ISSUE THREAD

**Issue by adekbadek** [Automattic/newspack-blocks#1636]
## As is

On the `epic/ras-acc` branch, when making a donation and selecting the "cover fees" option, the Stripe CC form fields get cleared.  

## To be

The form fields should not be cleared, as on `master` branch.

**Comment by miguelpeixe** [comment]
This is happening because of the new placement for the order review table. It's now being rendered as part of the same fragment as the payment method. The fragment change (to introduce the table) causes the HTML to be updated, which clears the form inputs.

I'm looking for alternatives so the order review table is rendered in the desired position but without impacting the payment method fragment HTML.

**Comment by miguelpeixe** [comment]
1205234045751551-as-1206299115205369/f
