### ISSUE TITLE
(5P) NHA: Remove “Newspack” name, and switch "articles" to "posts"

### ISSUE THREAD

**Issue by obenland** [Automattic/newspack-blocks#168]
If possible in the block itself

**Comment by marekhrabe** [comment]
We have got a green light to remove "Newspack" from the block title "Newspack Homepage Articles" in order to follow the naming convention of other blocks which don't have the duplicate brand as seen here:

<img width="394" alt="Screenshot 2019-11-21 at 12 44 08" src="https://user-images.githubusercontent.com/156676/69529898-68ab4f80-0f71-11ea-993a-57c72752ef4e.png">

We have also discussed the matter of using word _posts_ vs _articles_ and we have agreed to change articles to posts. paYJgx-jH-p2#comment-335

Both of these updates should be made directly to the block itself, not in any sort of special override file. This means changes will be seen in both single-block plugin and also the main newspack-blocks release. `newspack/homepage-articles` block slug should stay the same for now to maintain compatibility.

**Comment by retrofox** [comment]
> We have got a green light to remove "Newspack" from the block title "Newspack Homepage Articles" in order to follow the naming convention of other blocks which don't have the duplicate brand as seen here

Great news! Thanks, Marek. Let me close this one, then.

**Comment by jeffersonrabb** [comment]
Could you take a look at the solutions in https://github.com/Automattic/newspack-blocks/pull/225? This should allow any needed alteration to  title, category, and registration name.

**Comment by retrofox** [comment]
https://github.com/Automattic/newspack-blocks/pull/228

**Comment by retrofox** [comment]
Closed by https://github.com/Automattic/newspack-blocks/pull/228
