### ISSUE TITLE
(2P) NHA: Test with newspack plugin and posts list block enabled.

### ISSUE THREAD

**Issue by obenland** [Automattic/newspack-blocks#172]
* Test with both blocks enabled
* Test with both blocks in a page/post.

**Comment by marekhrabe** [comment]
On a page with both blocks, the older shows a nudge for the user to switch. Otherwise, they don't interfere with each other and work well.

<img width="722" alt="Screenshot 2019-12-10 at 15 00 51" src="https://user-images.githubusercontent.com/156676/70537664-1ff2b980-1b61-11ea-87d4-87d6875a0761.png">

**Comment by marekhrabe** [comment]
I have also tested a combination of FSE (0.17, including Blog Posts Block) and Newspack Blocks on the same site. Those don't work together as they step on each others toes by both using `NEWSPACK_*` constants.

When you have FSE 0.17 and try activating Newspack Blocks:

<img width="1252" alt="Screenshot 2019-12-10 at 15 35 12" src="https://user-images.githubusercontent.com/156676/70538737-e622b280-1b62-11ea-847f-e6c084c6e9dd.png">

Considering Newspack Blocks are currently not even published to the plugin repo, I'm not worried too much about this incompatibility but we should also check whether Newspack sites include FSE. If they do, we need to add some more checks in place.

**Comment by jeffersonrabb** [comment]
> Considering Newspack Blocks are currently not even published to the plugin repo, I'm not worried too much about this incompatibility but we should also check whether Newspack sites include FSE. If they do, we need to add some more checks in place.

Current Newspack sites do not have FSE installed, but odds  are good they will in the future.

**Comment by marekhrabe** [comment]
Update! It looks like you can use these plugins side by side on a single site as long as you activate Newspack Blocks first and FSE second. 

If you do it the other way around, our safeguard checks in FSE for Newspack Blocks presence (linked below) don't trigger because Newspack Blocks are not yet marked as active in site options. This seems like a race condition that we can probably fix.

Related code that is supposed to ensure the plugin cross-compatibility

https://github.com/Automattic/wp-calypso/blob/de18db59f34af488ff47092e28b596ad9dade68a/apps/full-site-editing/full-site-editing-plugin/full-site-editing-plugin.php#L326-L329

**Comment by marekhrabe** [comment]
Testing done in various scenarios. Issues coming from this raised separately
