### ISSUE TITLE
(2P) Posts List: Optional: Upgrade nudge

### ISSUE THREAD

**Issue by obenland** [Automattic/newspack-blocks#173]

**Comment by olaolusoga** [comment]
_Adding some context_

**Description**
The newspack article block does a better job visually handling blog post management on a page/post than the blog post block. When a person inserts the blog post block, we want to suggest the article block so they are aware of it.

**Flow**
![Screen Capture on 2019-11-05 at 08-45-19](https://user-images.githubusercontent.com/1382943/68213200-1a75e280-ffa9-11e9-9b11-56cce81fa01a.gif)

**Comment by olaolusoga** [comment]
Here's a mock for introducing a notice to prompt folks to switch from the blog post listing block to Newspack homepage article block. 

![Blog post listing to Article block 1](https://user-images.githubusercontent.com/1382943/68555452-db59ee00-03fb-11ea-850c-f665cb105685.jpg)

Placing the notice within the block would be the ideal path due to it being the most contextual. 

Also reason for not doing a informational tooltip, or something that points to the icon that houses the “Transform to: Newspack homepage articles”:
1. there isn’t really a tooltip like pattern in Gutenberg for that. Don’t want to introduce random components
2. Having the notice within the block puts it front and center. At the moment there isn’t a close option because I’m assuming we want folks to switch since we’re recommending it.
3. Any option outside of being a notice within the block seems agnostic, and can be speaking to anything on the page/post.

**Question:** are there plans to deprecate the blog post listing block, and replace it with the Newspack article block? If so, once deprecated, will the newspack article block be renamed to something more inline with “blog posts”?  If not, why? … We should consider it, since most folks know “blog posts” vs “homepage articles”

**Comment by marekhrabe** [comment]
being worked on here: https://github.com/Automattic/wp-calypso/pull/38051

**Comment by obenland** [comment]
Fixed in https://github.com/Automattic/wp-calypso/pull/38051
