### ISSUE TITLE
Homepage Blocks: is always applying `.aligncenter` class

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/newspack-blocks#26]
I noticed this while working on the Newspack theme:

When you insert the a homepage block and publish it, it applies the class `.aligncenter`. 

I suspect this is related to the block not supporting any alignments, though I'm not sure why it defaults to center. Currently this class causes it to apply some incorrect styles from the theme to the block.

**Comment by laurelfulford** [comment]
Noting that the visual issues have been fixed in the theme in https://github.com/Automattic/newspack-theme/pull/34 -- so this isn't an urgent issue to fix, just more weird than anything.

**Comment by iamtakashi** [comment]
I'd like this issue to get attention since the block is going to be available to a wider audience/themes. Many themes reasonable change text alignment inside `.aligncenter` to be centred-alignment, and the block doesn't look good. @Automattic/ajax

Editor:
<img width="1792" alt="Screenshot 2019-12-03 at 12 55 24" src="https://user-images.githubusercontent.com/908665/70052937-47c7a780-15cc-11ea-8075-7c98c210bd66.png">

Front-end:
<img width="1792" alt="Screenshot 2019-12-03 at 12 55 32" src="https://user-images.githubusercontent.com/908665/70052951-51e9a600-15cc-11ea-8e65-aad187660f17.png">
