### ISSUE TITLE
NHA: Image shape/cropping doesn't work

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/newspack-blocks#281]
**Describe the bug**
We can choose the image shape/cropping on the editor, but we can't see it live on the site.

**To Reproduce**
1. Add the NHA block
2. Select to display featured images
3. Choose one of the image shapes
4. Publish the post/page

**Expected behavior**
To see the selected shapes on the live site.

**Comment by claudiulodro** [comment]
I've tracked this down. The issue is related to what #229 was trying to do: package things up so the block can be stand-alone. As part of #229, the `add_image_sizes` method was moved into the `Newspack_Blocks` class, however [the hook that registers the image sizes](https://github.com/Automattic/newspack-blocks/pull/229/files#diff-ee7bb8e53cb0f3bb514134947e2d6590R22) was left in `newspack-blocks.php`. Therefore, the block image sizes aren't getting registered in the FSE plugin since `add_image_sizes` isn't hooked to anything in FSE (@Automattic/ajax).

My recommended solution is to move `add_action( 'after_setup_theme', array( 'Newspack_Blocks', 'add_image_sizes' ) );` into the `Newspack_Blocks` class (PR incoming).

**Related**: There is [a bug in the `image_size_for_orientation ` method](https://github.com/Automattic/newspack-blocks/pull/229/files#diff-040e9f02353d52b5385dfb8b546fdd31R235-R244), where if no image is matched it will return `null`, resulting in class names like `size-` for the image. Some sort of default fallback size should be used when no thumbnail is found (maybe the full size):

<img width="556" alt="Screen Shot 2019-12-12 at 9 31 06 AM" src="https://user-images.githubusercontent.com/7317227/70735226-9f4bce80-1cc2-11ea-9102-fd0b6d5ec5a1.png">

I'll tack a fix for that onto my upcoming PR.
