### ISSUE TITLE
Load More button: does not handle private blog

### ISSUE THREAD

**Issue by carinapilar** [Automattic/newspack-blocks#306]
**Describe the bug**
When you activate the Load More button on the block, it doesn't load the posts, it shows the message _"Something went wrong. Please refresh the page and/or try again"_.

**To Reproduce**
1. Go to Pages and create a new page
2. Add the Blog Posts block
3. Activate the option _"Show "More" Button"_ on the block
4. Publish the page

**Screenshots**
When you click on the button to load more posts, this is what shows up, including the errors on the console:

![BlogPostsBlock](https://user-images.githubusercontent.com/16104522/71194433-a8144580-226a-11ea-9a23-289d381e7fa3.png)

**Expected behavior**
To load more posts.

**Comment by adekbadek** [comment]
This is caused by the site being private (set in site settings) - hence the `403` error codes. "Load more" makes a request to `https://public-api.wordpress.com` in this case, and it does not return content for a private blog.
I'll rename the issue.

**Comment by obenland** [comment]
@WunderBart It doesn't look like we're sending an Authentication header with our requests, which results in the user not being set up on the API side and the private site check failing.

**Comment by obenland** [comment]
Would this documentation about wp api authentication help get you started?
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

**Comment by WunderBart** [comment]
> Would this documentation about wp api authentication help get you started?
https://developer.wordpress.org/rest-api/using-the-rest-api/authentication/

I tried setting the nonce as suggested in the guide but got the `Request header field x-wp-nonce is not allowed by Access-Control-Allow-Headers in preflight response.`. I'm trying to use the [wpcom-proxy-request](https://github.com/Automattic/wpcom-proxy-request) lib right now - we'll see how it goes!

**Comment by getdave** [comment]
So this is the `OPTIONS` request failing right? Which means WPCom is setup to reject this header. Perhaps WPCom is overly strict in this regard? If we have the auth details surely we should be able to access the site data.

**Comment by WunderBart** [comment]
>If we have the auth details surely we should be able to access the site data.

I believe the issue is that we actually don't have the necessary auth details at hand as we do, e.g. in Calypso, where the `oAuthToken` is kept in the `localStorage` (see [auth-wrapper.jsx](https://github.com/Automattic/wp-calypso/blob/master/apps/notifications/src/standalone/auth-wrapper.jsx)) and can be used anytime to perform an authenticated request. In the front-end of the site, even if the user is signed in that token doesn't seem to be available, unfortunately. I don't think we can use [implicit oAuth](https://developer.wordpress.com/docs/oauth2/) here, but it might be worth to take a look at the [admin-ajax.php way of performing requests](https://www.smashingmagazine.com/2011/10/how-to-use-ajax-in-wordpress/) (props @obenland).
