### ISSUE TITLE
Blog Posts block: allow multiple instances on a page

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/newspack-blocks#317]
**Describe the bug**
After adding one Blog Posts block to a blank page on a WordPress.com site, you can't add another. 

This can be circumvented by duplicating the code for an existing Blog Posts block in the Code Editor, then switching back to the Visual Editor and customizing the new block.

**Screenshots**
When trying to add a second block:
![](https://d.pr/i/dJQyvN+)

**Expected behavior**
Given that this block is used multiple times on a Newspack home page, I figure it was meant to be used multiple times per page in general.

**Comment by adekbadek** [comment]
Hi, thanks for reporting that. This is actually [implemented in Calypso](https://github.com/Automattic/wp-calypso/blob/master/apps/full-site-editing/full-site-editing-plugin/blog-posts-block/editor.js#L36) (which imports the Blog Posts block, so that it's available on wordpress.com).
According to the issue that requests this restriction (https://github.com/Automattic/wp-calypso/issues/38404), this is a temporary thing, but feel free to open an issue there.

**Comment by kspilarski** [comment]
Same case in 2666978-zd - Blog Post block can only be used once per page.
