### ISSUE TITLE
Blog Posts Block: Appears "Broken" at full width, with grid view

### ISSUE THREAD

**Issue by ianstewart** [Automattic/newspack-blocks#334]
Screenshot on a page with Twenty Twenty active, MacOS Chrome:

![image](https://user-images.githubusercontent.com/545779/72390201-c0537500-36ef-11ea-849b-d46f7c87b5e7.png)

The edges of the screenshot are the edges of the browser chrome.

**I expected:**

To have some sort of limit on the block built in to prevent this, perhaps matching the built-in columns?

cc @michaeldcain and @obenland

**Comment by laurelfulford** [comment]
Hey @ianstewart! 

> To have some sort of limit on the block built in to prevent this, perhaps matching the built-in columns?

Unfortunately, this is a theme-level issue, and we probably shouldn't be fixing in the block, in case it causes something unexpected:

Gutenberg leaves it to theme developers to determine how to handle wide and full styles -- on the front end, no styles are added for them, just classes. 

Depending on how those styles are approached, this means themers also have to add styles for specific blocks, since there are some you'd probably want to go right to the edges (group, image, cover blocks), and others you wouldn't (basically anything with text: columns, pullquotes, captions, and this one).

Twenty Twenty already has some explicit styles in place to avoid the text hitting the edges for Core blocks, like columns:

```
.wp-block-columns.alignfull,
.alignfull:not(.has-background) .wp-block-columns {
	padding-left: 2rem;
	padding-right: 2rem;
}
```

Or for captions:

```
.alignfull > figcaption,
.alignfull > .wp-caption-text {
	width: calc(100% - 4rem);
}
```

Ideally, styles to fix this issue in this block would be added on the theme-level, too, to line up with how other full-width blocks need to be handled. Because of that, I'm going to close this issue, but I'm happy to discuss it further here! Also, please let me know if you'd like me to spin up a new issue in the themes repo for this!

**Comment by ianstewart** [comment]
> Also, please let me know if you'd like me to spin up a new issue in the themes repo for this!

If it's no trouble, for sure! Thanks, Laurel.

**Comment by laurelfulford** [comment]
Not at all! It's been a while since I've had an excuse to go to that repo 😄 

https://github.com/Automattic/themes/issues/1773
