### ISSUE TITLE
Blog Posts Block Ignores Verse/Preformat/Formatting. Displays in Paragraph.

### ISSUE THREAD

**Issue by scosgro** [Automattic/newspack-blocks#398]
#### Steps to reproduce
1. Create a post, and add Preformatted Block, and/or a Verse Block to the post, as if you're writing a poem that has some sort of formatting to it. Publish the post.
2. Create a new post in a Paragraph Block, make it center aligned, with a few words per line (like a center aligned poem, maybe 10 lines long). Publish the post. 
3. Create a page, and add the Blog Posts Block. Publish the page. 
4. The poems will all show up as a single paragraph, without any spacing/line breaks/formatting/context. 
5. The workaround is to copy/paste the HTML of the verse block into the Excerpt box, but if you're using a Paragraph Block, and try to use that HTML as the excerpt, it will break, and only the first line will follow the formatting, since the excerpt will create new unformatted `<p>` tags for each additional line. 

#### What I expected
The formatting used in the post to appear as the excerpt. 

#### What happened instead
It's in a single paragraph, with no line breaks, no alignment, no spacing, etc. 

#### Browser / OS version
All.

#### Screenshot / Video
![VerseBlock](https://user-images.githubusercontent.com/30731356/73017500-d1c60c80-3dd4-11ea-9469-01e871231fcc.png)
![blockpostsblock](https://user-images.githubusercontent.com/30731356/73017506-d38fd000-3dd4-11ea-9a41-63f8e804b538.png)

#### Context / Source
#empathy #reallife  #painpoint  #user-report

**Comment by laurelfulford** [comment]
Thanks for reporting this, @scosgro!

> The poems will all show up as a single paragraph, without any spacing/line breaks/formatting/context.

This is the default behaviour for `the_excerpt()`; the block would basically need an option to switch it to `the_content()` to change this, which we do have an enhancement request for in #385  :) 

> but if you're using a Paragraph Block, and try to use that HTML as the excerpt, it will break, and only the first line will follow the formatting, since the excerpt will create new unformatted <p> tags for each additional line.

This is kind of strange! I was only able to recreate it on WP.com -- it's like it's passing it through `wpautop()` but I would have expected it to respect the paragraphs that are already there. As an added work around, if you remove all the spaces between the paragraphs -- so you kind of end up with something like the below -- it seems to work:

```
<p class="has-text-align-center">this is a poem written in paragraph form</p><p class="has-text-align-center">it is amazing<br>This one includes a line break</p><p class="has-text-align-center">Another new paragraph that wraps to its own line because it is longer and I wrote more stuff, then<br>line break<br>line break<br>and another... line break.</p>
```

![image](https://user-images.githubusercontent.com/177561/76470618-d27b2800-63ad-11ea-8c4a-cfaf63f0caaf.png)

I'm going to close this partially as a duplicate (with the existing full content feature request), and partially as not related to the block, since other areas that use `the_excerpt` seem to have the same weird output if you don't remove all of the spaces (archives are a common example). But just let me know if you have any questions at all about the above!
