### ISSUE TITLE
Blog Posts Block: Load More Posts button doesn't appear even though there are more posts to load

### ISSUE THREAD

**Issue by susanjanec** [Automattic/newspack-blocks#404]
**Describe the bug**
User is using a blog post block to display posts to 5 posts at a time. The Load More button does appear as expected for the next 5 posts, but it doesn't seem to appear after the 2nd time even though there are more posts.

When I tested this on my own site, at a certain point when trying to click on the Load More button for more posts, the Load More button will stop appearing, even though there are still more posts that can load.

**Screenshare/Screenshot**

https://d.pr/i/AjoWdA 
https://d.pr/i/ADm2an

**To Reproduce**
Steps to reproduce the behavior: I tested this on my own site: https://susanjane.blog/testing-blog-posts-block/
1. Click on `Load More Posts` to load next 5 posts, then again, and then again.
2. The last post at the bottom should be `BIRTHDAY BOOK CLUB` which is not the last post published (there are more before this). You won't see the `Load More Posts` button, however, there are 12 published posts before this post, so the `Load More Posts` button should appear to display more posts.

**Expected behavior**
The Load More Posts button should appear at the bottom to load the next 5 posts until there are no more published posts to display. For Reference, on my site, the last published post should be titled `The Coolest Hair`

**Comment by susanjanec** [comment]
Report on 2772505-zen

**Comment by SiobhyB** [comment]
I was able to replicate this also after another report in 19354723-hc.

**Comment by susanjanec** [comment]
Another report in 20142631-hc

**Comment by pauljacobson** [comment]
We have another report of this issue in 2978696-zen 

The user has enabled the "Show more posts" option, but the button doesn't display on the page. See here:

![Screen Shot 2020-05-16 at 12 57 43 PM](https://user-images.githubusercontent.com/2912202/82137686-f67e3e00-9822-11ea-894f-bc3ba8304952.png)

This is how the page renders:

![Screen Shot 2020-05-17 at 09 43 38](https://user-images.githubusercontent.com/2912202/82137701-0eee5880-9823-11ea-9108-2c070ae7391d.png)

**Comment by sdixon194** [comment]
Another case in 21234195-hc.

**Comment by zdenys** [comment]
Another case here https://wordpress.com/it/forums/topic/non-compare-il-pulsante-di-caricamento-articoli/

**Comment by villanovachile** [comment]
Just had this issue in 3037601-zen / 21670415-hc

I've done some pretty extensive testing on this, and can reproduce the issue as follows:

Make 60 posts (using a plugin such as FakerPress)

Create a Blog Posts Block with Load More enabled in Display Settings. When changing the number of items, clicking Load More eventually stops loading posts and are capped as follows:

Number of Items - 5, posts are capped at 30

Number of items - 10, posts are capped at 40

Number of items - 11, posts are capped at 33

Number of items - 12, posts are capped at 36

Number of items - 13, posts are capped at 39

Number of items - 14, posts are capped at 42

Number of items - 15, posts are capped at 45

Number of items - 16, posts are capped at 48

Number of items - 17, posts are capped at 48

Number of items - 20, posts are capped at 40


As you can see, there appears to be a direct correlation with the number of Items entered, so that the total number of posts to be displayed using "Load More" is evenly divided by the number of items entered. Any remainder posts are not displayed. 

There are a few exceptions to this, such as when items to be displayed are 5, 10, or 20, which appears to have a hard cap at 40.

This issue occurs regardless of theme, or using Calypso/WP Admin dashboards.

**Comment by eoinsav** [comment]
Another report in 21211534-hc

The user has 38 Posts and the Blog Post Block set to display 5 Posts at a time. They stopped loading at 25 and the Load More button disappeared.

It kept stopping at a random number of Posts no matter how many were chosen to load at a time.

**Comment by tbradsha** [comment]
6889940-hc

**Comment by katiebethbrown** [comment]
3262479-zd-woothemes

**Comment by tanjoymor** [comment]
3282681-zd

**Comment by paulostp** [comment]
3329555-zd

**Comment by fresatomica** [comment]
Another report of this [here](https://wordpress.com/forums/topic/show-all-posts-3/).

It seems like this issue was also mentioned here: https://github.com/Automattic/newspack-blocks/issues/438

**Comment by pbking** [comment]
+1
23710523-hc and #3398373-zen

**Comment by villanovachile** [comment]
another report: 25108946-hc and 3432130-zen

**Comment by supernovia** [comment]
Looks like there are a few related issues open, but this one has the best number, so, noting this case:

https://wordpress.com/forums/topic/cant-see-my-older-post/#post-3583034

**Comment by supernovia** [comment]
We have another case here:
https://wordpress.com/forums/topic/all-the-posts-are-not-showing-up/

Any idea who we need to ping on this?

**Comment by soatok** [comment]
Each press of the "Load More" button appends another ID to the exclude parameter, and the page number keeps getting increased too. Because both mechanisms are being triggered, the "what's the next URL?" is probably short-circuiting at approximately half the number of posts.

(I set the number to show per page to 1 to study the incremental behavior, and specifically the HTTP request parameters.)

**Comment by soatok** [comment]
I proposed a workaround in #628 but the full, correct fix might be a little more involved.

**Comment by supernovia** [comment]
Thanks for that @soatok . I ran into another case here today:
https://wordpress.com/support/import/#import-content-from-another-platform

**Comment by synora** [comment]
Another report. 3591685-zen.

**Comment by iamgabrielma** [comment]
Another one at 3602566-zen

**Comment by donalirl** [comment]
Another case in #26727364-hc and there are similar reports in #438 and https://github.com/Automattic/wp-calypso/issues/48598

**Comment by soatok** [comment]
Considering cases keep coming in, we [know what's causing it](https://github.com/Automattic/newspack-blocks/issues/404#issuecomment-726454648), and have [a possible fix for it](https://github.com/Automattic/newspack-blocks/pull/628), what's blocking Automattic from applying the fix?

**Comment by hngdny** [comment]
Another report on #26984312-hc

**Comment by soatok** [comment]
I'm glad to see this fixed.

Final question: What's the usual Github Release -> Patch Deployed timeline for WordPress.com users? (i.e. when can we expect to see this fixed?)

**Comment by dkoo** [comment]
@soatok I'll update this thread once you can expect to see the fix on WordPress.com.

**Comment by dcoleonline** [comment]
Just noting that another report happened in 27164170-hc on WordPress.com

**Comment by felipelousantos** [comment]
One more report on 27165318-hc (follow-up 3673082-zen).

**Comment by supernovia** [comment]
Yay! Thanks!  We'll need to follow up here once that's out:
https://wordpress.com/forums/topic/load-more-posts-doesnt-load-all-posts/

**Comment by kdevnel** [comment]
Awesome news on this! Thanks for the work for a resolution. Noting to follow-up with 3674661-zd-woothemes once this is live on WP.com

**Comment by supernovia** [comment]
Excited to follow up here, too: https://wordpress.com/forums/topic/how-can-i-scroll-all-the-way-back-to-start-of-blog/#post-3625181

**Comment by thesacredpath** [comment]
Will need to follow up here as well: 3685981-zen

**Comment by jerrysarcastic** [comment]
Also reported in https://wordpress.com/forums/topic/free-blog-not-showing-oldest-posts/

Noting here so we can follow up

**Comment by dkoo** [comment]
I'm working on getting this fix synced downstream to WP.com. We'll need to land this PR first: https://github.com/Automattic/newspack-blocks/pull/677

I'll update this issue as I have more info on timing.

**Comment by supernovia** [comment]
Thanks @dkoo . We're mostly noting issues so we can follow up with the users once it's out. 🥳

**Comment by dkoo** [comment]
Opened a PR to pull these changes into WP Calypso: https://github.com/Automattic/wp-calypso/pull/49493

**Comment by dkoo** [comment]
Just to close the loop on this, the Load More fix has been deployed to WP.com. (It introduced some more regressions, but that's for another time. 🤣)
