### ISSUE TITLE
Articles Carousel: Repeated date on frontend if post has been updated

### ISSUE THREAD

**Issue by jeryj** [Automattic/newspack-blocks#452]
If a post has been updated and is included in the Articles Carousel, it will show both the publish date and updated date.

**To Reproduce**
1. Have two or more posts with featured images
2. Update one of the posts with new content
3. Add the articles carousel to a page
4. Publish the page 
5. Visit the page and see that the post in the carousel shows a repeated date

**Screenshots**
<img width="1590" alt="Screen Shot 2020-05-01 at 9 41 21 AM" src="https://user-images.githubusercontent.com/967608/80813605-f11cc480-8b8f-11ea-9423-1ebbd89b9518.png">

**Expected behavior**
I think it should only show the publish date _or_ the updated date.

**Comment by jeffersonrabb** [comment]
@laurelfulford do you recall why we added the update date here? https://github.com/Automattic/newspack-blocks/blob/master/src/blocks/homepage-articles/templates/article.php#L126

Testing the standalone plugin I never see the doubled date so I haven't been able to replicate this issue. Would there be any harm in removing it from Homepage Posts and Carousel?

**Comment by laurelfulford** [comment]
It's part of a microformats spec that's often used in themes: 

http://microformats.org/wiki/hentry

The doubled date is probably coming from the carousel not explicitly hiding the updated version of the date -- we had the same issue with the Homepage Posts block, because it was assuming that all themes would be hiding that class (which is a bad assumption!).

I think it's probably safe to remove, since we're not implementing it fully (the posts in these blocks don't have the `.hentry` class; I'm not sure we're using all the classes we should). If we opt to add that down the road, we'd want to make sure that was all done correctly -- as is I think it's a partial copy-pasta from the theme :)
