### ISSUE TITLE
Blog Posts Block: Add option for manual Continue Reading link

### ISSUE THREAD

**Issue by tijosh** [Automattic/newspack-blocks#495]
**Is your feature request related to a problem? Please describe.**

Users cannot currently:

1. Display a Continue Reading link and
2. Control what comes before the link

If you set a manual excerpt or put a More block into the posts, no `Continue Reading` link is shown. 

**Describe the solution you'd like**

Add option to manually include a Continue Reading button

**Context**

#21404141-hc

**Comment by laurelfulford** [comment]
Just noting for anyone looking into this:

The 'Continue Reading' link will be coming from the theme, rather than the block. There are a number of themes that replace the `[...]` at the end of automatically generated excerpts with something else by filtering `excerpt_more` ([example](https://github.com/Automattic/themes/blob/b6ae2c8a45c2317cef960b8c0ef94da55427ffa5/textbook/inc/template-tags.php#L181-L201)). The reason the link doesn't happen with Custom Excerpts is that the `[...]` is not there, since it's assumed that those would end with a full stop and not need an ellipsis. 

If we added this enhancement, we might want this to fully replace the `[...]` for automatically generated excerpts (so theme filters won't interfere with it), and have the option to always include a customizable link at the end of the excerpt to the full post.

**Comment by tijosh** [comment]
> and have the option to always include a customizable link at the end of the excerpt to the full post.

I think this would be helpful. It allows consistency no matter how the posts are constructed.

**Comment by dcoleonline** [comment]
Also requested in 3264365-zen, so if this is ever added, we should notify them.

**Comment by mikeicode** [comment]
Requested 26351581-hc
