### ISSUE TITLE
Blog Posts block: Links don't open in new tab when set in post

### ISSUE THREAD

**Issue by brookewp** [Automattic/newspack-blocks#521]
**Describe the bug**
When a link within a post is set to open in a new tab, the link opens within the same window when accessing through Blog Posts block. 

Not 100% sure if it is a bug or if it's intentional, but it seems like the post behavior should be mimicked in the same Blog Posts block post.

**To Reproduce**
1. Add link to a post with 'open in new' tab option
2. Add Blog Posts block to a page
3. Click on link in the post where Blog Posts block has been added
4. See link opens in same tab/window

**Expected behavior**
I expected the link target to be added to the link in the Blog Posts preview so it would work the same as the content in the post.

**Comment by laurelfulford** [comment]
Hey @brookewp! I tried to recreate this, but I think I might be missing something:

The blog posts block only displays an excerpt, so I added a custom excerpt, and included a link with the `target="_blank"` attribute in that excerpt text. When I click on the link doing that, it does open in a new window. 

However it sounds like you're adding a link in the post content, and it's displaying in the blog posts block. If that's the case, we might not be talking about the same block -- do you have an example to link to where this is happening? There's also an equal chance that I'm just getting confused, but that should help straighten things out :) thanks!

**Comment by brookewp** [comment]
Hey @laurelfulford - thanks for taking a look! I have an example added to a test site here: https://brookewp.wordpress.com/blog/
This also shows the same issue as in #520 

Let me know if you need anything else from me!

**Comment by laurelfulford** [comment]
Thanks @brookewp! I'm able to recreate this. 

I'm not entirely sure what's happening here, but it does not seem unique to the Newspack Blocks:

* I can recreate this only on WP.com.
* I can recreate using the full URL as the link text, but not if I link a single non-URL word -- in that case it's stripped out, which is the expected behaviour for `the_excerpt`. Adding the text `https://www.google.com` and linking it will work; adding the word "Google" and linking it will not. 
* The above can also only be the only content in the post -- if it's just at the start of the post, it also will not be linked. 
* It happens wherever `the_excerpt` is used, not just in the block: if I use a theme that uses excerpts for, say, search results, the same issue happens there. If you switch your test site to Twenty Twenty and use the search to find your post, you'll get the same link weirdness in the search excerpt.  

I expect there's a filter or something on WP.com that's doing this, but I haven't had any luck finding it. I think, too, that a filter is turning the separate dashes into the em-dash, and it being a URL is not expected in an excerpt (this is totally a guess though!). 

Anyway, that's a very long way to say this issue and #520 don't appear to be specific to the Newspack blocks, but how WP.com handles linked URLs in excerpts when that is the only thing in the content. 

I'm going to close these as they're not specific to this block, but I'm not really sure the best place to move these reports, though 😕 Please let me know if you have any questions at all about the above!
