### ISSUE TITLE
Blog Post Block: When nested in cover block, the featured images inherit cover block style

### ISSUE THREAD

**Issue by benchilcote** [Automattic/newspack-blocks#560]
**Describe the bug**
Blog Posts block, when nested inside a cover block, the featured images inherit the cover block's style 

**To reproduce**
1. Add a cover block
2. Inside the cover block, add a blog post block and adjust so featured image are displayed
3. Apply a style to the top level cover block (Bottom Wave, Top Wave)
4. The wave style will apply to any featured images within the blog post block that is nested in a cover block

![Screen Capture on 2020-07-31 at 15-16-34](https://user-images.githubusercontent.com/11636210/89069335-f6311180-d340-11ea-8a17-59d1daf57578.gif)

**Expected behavior**
I would expect the blog post block to not inherit the style and maintain their own style independent of the parent block

**Screenshots**
![Screen Shot 2020-07-31 at 3 13 55 PM](https://user-images.githubusercontent.com/11636210/89069136-95093e00-d340-11ea-9698-7a834d5e57cf.png)

Ref: 3171630-zen

**Comment by laurelfulford** [comment]
I can't recreate this issue:

![image](https://user-images.githubusercontent.com/177561/166306087-046bd380-c6c2-4e65-b7a0-e4f3c2abf9ff.png)

It looks like this style at least now targets this CSS selector:

`.wp-block-cover:not(.components-placeholder):not(.is-placeholder).is-style-bottom-wave`

... so it should only be applied on the containing `wp-block-cover` element, and not any image inside. My best guess is that this changed between when this issue was filed and now, and that the original styles were a bit more general. 

I'm going to close this issue, but @benchilcote please do let me know if I'm missing something here -- thank you!
