### ISSUE TITLE
Blog Posts Block: Norwegian translation for Blog Posts block "Continue reading..." (i18n)

### ISSUE THREAD

**Issue by retnonindya** [Automattic/newspack-blocks#582]
**Describe the bug**
I unable to find anything on GlotPress, so I decided to ask here. This is non-urgent at all. I don't know where to ask, so... 😅

This is user report. They are well-versed in Norwegian language (Norsk) and informed that the translation for "Continue reading..." on Blog Posts block is incorrect.

Currently, the translation is "Fortsett å les", while the correct translation should be "Fortsett å lese" or "Les mer".

I tried searching GlotPress to no avail. I checked here:
https://translate.wordpress.com/projects/wpcom/no/default?filters%5Bterm%5D=continue+reading

And all translations are correct.

An Automattician assisted me on updating the translation on Varia theme (since the website is using Hever theme -- Varia child theme):
https://translate.wordpress.com/projects/wpcom/themes/varia/no/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=258659&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

But the issue persists. I expected when the translation is accepted/validated, it should be reflected properly on the Blog Posts block immediately, but it didn't.

I'm thinking this might be related to the block, not the theme -- hence, this GH issue. 

Can anyone assist me on this? Do we have translation/i18n project for blocks? If yes, where should I check for translation project on Newspack Blocks? Thank you.

**Comment by laurelfulford** [comment]
Hi @retnonindya! 

Confusingly, the string "Continue Reading..." doesn't come from the block -- it uses the default ending for `the_excerpt()`, which is the not-linked `[...]` string. Some themes -- like Varia -- add a filter to `the_excerpt() to change the `[...]` to something else, like a link or button -- that filter gets picked up by anything on the site using `the_excerpt()`, including the block. The translations for whatever that text is would also be coming from the theme. 

Varia uses `the_excerpt()` for search results as well; I tried switching my test site to Hever and the language to Norsk and ran a search, and I'm still seeing the incorrect translation there, too:

<img width="804" alt="image" src="https://user-images.githubusercontent.com/177561/91341631-a18d8480-e78e-11ea-8487-967c00bb1853.png">

My best guess is that it hasn't updated yet, or the changes haven't been deployed? It could be worth checking with the i18n folks to verify if it should be updated, and what could be happening. I'm going to close this issue since it isn't related to the block, but if you have any questions at all about the above, please let me know in the comments!

**Comment by retnonindya** [comment]
Hi @laurelfulford!

Thank you so much for the explanation! And yep, folks on i18n helped me on checking the translation and yes! It's coming from Varia! 🎉  Thank you so much, Laurel! TIL, we deploy theme translation every day on 3 UTC! The user has responded, informed that the translation is now correct! Yay! Thank you!

**Comment by laurelfulford** [comment]
Yay!! Thanks for confirming, @retnonindya!
