### ISSUE TITLE
Reusable blocks preventing a post from being published

### ISSUE THREAD

**Issue by iamstevebeatty** [Automattic/newspack-blocks#729]
From SA Report
https://newspack-pub.slack.com/archives/C011YNC4B24/p1616111778055000?thread_ts=1615901237.004700&cid=C011YNC4B24

They try to deselect the option to save the reusable block, but it won't publish unless that box is checked. 

**Describe the bug**
A clear and concise description of what the bug is. Please be as descriptive as possible; issues lacking detail, or for any other reason than to report a bug, may be closed without action.

**To Reproduce**

**Screenshots**

**Expected behavior**

**Comment by laurelfulford** [comment]
Hi @iamstevebeatty! It looks like this is already reported in the Gutenberg repo, so I'm going to close this issue to defer to that one -- since the behaviour is based in the editor (and not something we can control/change from our plugin), if it's changed, it will need to happen there:

https://github.com/WordPress/gutenberg/issues/29269
