### ISSUE TITLE
Newspack Block slow query issue.

### ISSUE THREAD

**Issue by harishtewari** [Automattic/newspack-blocks#808]
Unfortunately, using post__not_in can dramatically slow down a query. Instead, need to programmatically skipping via PHP: https://wpvip.com/documentation/performance-improvements-by-removing-usage-of-post__not_in/.

Getting lots of time 503 back-end fetches failed error. Because of slow query.
https://github.com/Automattic/newspack-blocks/blob/master/includes/class-newspack-blocks.php#L433

**Comment by claudiulodro** [comment]
The first versions of the posts block [used to use the approach where we would get more posts than needed and programmatically skip the extras](https://github.com/Automattic/newspack-blocks/pull/61/files) because of that recommendation. It was more fragile than using `post__not_in`, and we detected no measurable difference in page load time between performance of the two approaches in our testing. 

Having the posts block e.g. fetch 80 posts then discard 75 of those posts, then the next block fetches 85 posts and discards 80, then the next fetches 90 and discards 85, etc. is also not ideal from a performance standpoint. It's hundreds of extra posts fetched and discarded over the rendering of a homepage.

I don't believe there is an ideal solution for this use-case -- the more homepage posts blocks there are on a page the more processing is required.

**Comment by pradeep910** [comment]
@claudiulodro How the newspack sites handle the posts_not_in queries? Do they have any special module to optimize queries or caching mysql queries differently?
I think any bigger site with traffic will give performance issues.
