### ISSUE TITLE
Rename to @automattic and publish to npm

### ISSUE THREAD

**Issue by scinos** [Automattic/newspack-blocks#849]
**Is your feature request related to a problem? Please describe.**

Right now external consumers that want to depend on `newspack-blocks` have to consume this package using a git url. Example:

```
dependencies:{
    newspack-blocks: "github:Automattic/newspack-blocks#v1.33.0"
}
```

Consuming it from a git url is problematic for a few reasons, mainly because there is no guarantee that the tag/branch `v1.33.0` will continue to exist or that it will always point to the same commit. Publishing it to NPM will make things easier for consumers.

Another problem is the name. Right now, the package `newspack-blocks` _already exists_ in NPM and it was removed because it contained malicious code (https://www.npmjs.com/package/newspack-blocks). Likely it has been the target of package squatting (https://www.flyingpenguin.com/?p=31813). I strongly recommend we rename it to `@automattic/ newspack-blocks`

**Describe the solution you'd like**

- Rename the package to `@automattic/newspack-blocks`.
- Publish it to NPM

**Comment by swissspidy** [comment]
PHP projects like this should really be published on Packagist, not npm.

**Comment by scinos** [comment]
> PHP projects like this should really be published on Packagist, not npm.

I guess we could do both. Projects like https://github.com/Automattic/wp-calypso consume this package mainly for its JavaScript files.

**Comment by adekbadek** [comment]
What's the use case for consuming this code via npm?

**Comment by scinos** [comment]
@noahtallen do you know the specific details?

**Comment by noahtallen** [comment]
We have a WordPress plugin which lives in the Calypso monorepo. This plugin is used to deploy newspack blocks to WordPress.com simple and atomic sites. There are two steps to including the newspack blocks source code in this plugin:

1. Retrieve the code for newspack blocks
2. Run a few scripts to transform things like the textdomain into the textdomain of the target plugin

Until recently, we were just adding the URL to the github zip download for a release in `package.json`, which lets our package manager handle step 1. Then, during our build step, we run the scripts to handle step 2. (This build script basically copies from node_modules to a location in the plugin where it can be included by a wrapper.) We switched to publishing to npm rather than the GH release URL because that resolved some issues with newer versions of `yarn`. 

I mean, basically the whole situation is not ideal, but there really are no "ideal" ways to sync code to WordPress.com from other repos. 

In the past (like a year or more ago), we just copied the code directly into source control, but that was confusing because it gives the expectation that folks are meant to edit newspack blocks source code for wpcom in the Calypso repo, which is not the case.

Theoretically, we could use `composer` to install new versions -- but our infra is really set up for JS rather than PHP, so we haven't done anything with composer beyond devtools like PHPCS.

That said if `composer install` downloaded it to a particular location, and then our build script copies the files in the same way from that location into the plugin in the right spot, we could probably make that work.

The only weird side effect is that we would still be compiling newspack blocks JS using our webpack config and dependencies. Theoretically, having the newspack block dependencies pulled in with yarn makes sure we don't introduce any incompatibilities. I don't know if that would have much of a real impact though.

The reason we have to compile newspack blocks JS using our webpack is because of the wrapper JS files which register newspack blocks under a different name for WordPress.com customers.

A lot of this stuff was figured out a couple of years ago, and I'm only passing it along second-hand. It's definitely an odd situation 😅

**Comment by adekbadek** [comment]
Hi @scinos – please take a look at what's distributed in the [latest pre-release](https://www.npmjs.com/package/@automattic/newspack-blocks/v/1.48.0-alpha.1) and let us know if that solves the problem.

**Comment by noahtallen** [comment]
👋 I (along with @Automattic/team-calypso-platform) am a good contact for this now that Sergio no longer works at Automattic, so I'm happy to take a look!

I'm testing it out here: https://github.com/Automattic/wp-calypso/pull/62829. BTW, what does the "alpha" thing mean? will stable releases be automatically tagged?

**Comment by noahtallen** [comment]
From what I can tell with some very brief testing, our workflow is compatible with the alpha version, and a brief test of the alpha update has the newspack blocks working successfully on WordPress.com

**Comment by adekbadek** [comment]
> BTW, what does the "alpha" tag indicate? will stable releases be automatically tagged?

It's a pre-release, we do regular releases every second Moday (one coming up today). Stable releases will be tagged, see https://github.com/Automattic/newspack-blocks/releases

**Comment by noahtallen** [comment]
Great!
