### ISSUE TITLE
New block: Author Profile List

### ISSUE THREAD

**Issue by gamebits** [Automattic/newspack-blocks#901]
The individual Author Profile block is very handy! But it's a manual placement, which means updating the staff roster page every time someone leaves or is hired. And, more important, it doesn't scale: One Newspack publisher from 40 to 350+ authors in just one year. Placing 350 author blocks and then keeping that list updated isn't feasible.

We should implement a new block that shows all authors in lazy-loaded fashion using the same template and display options as the individual Author Profile block. It would also have sort options (first/last name) and the option to show WordPress users, Co-Authors Plus guest authors, or both.

**Comment by dkoo** [comment]
So far this isn't presenting too much trouble, except for the lazy-loading aspect. Because CAP guest authors are posts and WP users are users, they require two separate queries whose results must be combined after query execution, which makes it difficult if not impossible to paginate the two types together without first getting _all_ of both types of authors. So in terms of requirements, I think we should just show all authors on the site and allow for an "exclusion" field that lets editors search for authors by name to have them not appear in the list.
